//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Trail
    {
        public int ID { get; set; }
        public Nullable<int> Action_By { get; set; }
        public string Terminal { get; set; }
        public Nullable<System.DateTime> Action_Date { get; set; }
        public string Activity_Type { get; set; }
        public string Action_Form { get; set; }
        public string Action_Table { get; set; }
        public Nullable<int> Transaction_ID { get; set; }
        public string Project_Name { get; set; }
    }
}
