//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BallotInfo
    {
        public int BallotID { get; set; }
        public int ResolutionApproveID { get; set; }
        public int ParlSessID { get; set; }
        public System.DateTime BallotDate { get; set; }
        public int RaisedStatus { get; set; }
        public int BallotEmpID { get; set; }
    }
}
