//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstitutentInfo
    {
        public int ConstitutentID { get; set; }
        public string ConstitutentArea { get; set; }
        public string ConstitutentBangla { get; set; }
        public string ConstitutentNumber { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
