//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignationInfo
    {
        public int DesignationID { get; set; }
        public string DesignationCode { get; set; }
        public string DesignationName { get; set; }
        public Nullable<int> Status { get; set; }
        public string DesignationNameBN { get; set; }
        public string Grade { get; set; }
    }
}
