//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocUpInfo
    {
        public int ID { get; set; }
        public string DocTypeCode { get; set; }
        public string DocTypeName { get; set; }
        public string DocName { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string DocRemarks { get; set; }
        public string FormName { get; set; }
        public string TrackNo { get; set; }
        public string PrNo { get; set; }
        public Nullable<int> UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
    }
}
