//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeInfo
    {
        public int UserID { get; set; }
        public string EmployeeCode { get; set; }
        public string UserName { get; set; }
        public string BanglaName { get; set; }
        public string FatherName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string UserType { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public int DepartmentID { get; set; }
        public string Email { get; set; }
        public string NationalID { get; set; }
        public string PhotoURL { get; set; }
        public Nullable<int> Status { get; set; }
        public string Signature { get; set; }
    }
}
