//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailTrack
    {
        public int ID { get; set; }
        public string ProNo { get; set; }
        public string TriggerType { get; set; }
        public string MailTo { get; set; }
        public string FormName { get; set; }
        public Nullable<System.DateTime> MailTime { get; set; }
        public string MailStatus { get; set; }
        public string SpecialMsg { get; set; }
        public Nullable<int> MailTypeID { get; set; }
        public string SMTPServer { get; set; }
    }
}
