//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberResolutionInfo
    {
        public int MemberResolutionID { get; set; }
        public string MemberResolutionDetail { get; set; }
        public Nullable<int> ResolutionSLNo { get; set; }
        public Nullable<System.DateTime> MemberResolutionDate { get; set; }
        public string MemberResolutionFIleURL { get; set; }
        public Nullable<int> ParlSessID { get; set; }
        public string EntryType { get; set; }
        public string AcceptStatus { get; set; }
        public Nullable<int> UserID { get; set; }
        public string AcceptanceComment { get; set; }
        public string RDNo { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public string SendTo { get; set; }
        public Nullable<bool> IsDraft { get; set; }
    }
}
