//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLConf
    {
        public int ID { get; set; }
        public Nullable<int> MH_ID { get; set; }
        public Nullable<int> SM_ID { get; set; }
        public string SM_Url { get; set; }
        public string Act_Type { get; set; }
        public string Dept_Code { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public Nullable<int> ML_ID { get; set; }
        public string Notify_For { get; set; }
    }
}
