//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLMng
    {
        public int ID { get; set; }
        public string ML_Name { get; set; }
        public string Mail_Sub { get; set; }
        public string Mail_Body { get; set; }
    }
}
