//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MNConf
    {
        public int ID { get; set; }
        public int SM_ID { get; set; }
        public int MH_ID { get; set; }
        public int RL_ID { get; set; }
        public string Sv { get; set; }
        public string Vw { get; set; }
        public string Dl { get; set; }
    }
}
