//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResolutionApprovalDTL
    {
        public int AID { get; set; }
        public Nullable<int> ResolutionApproveID { get; set; }
        public Nullable<int> MemberResolutionID { get; set; }
        public string RDNo { get; set; }
        public Nullable<int> ParlSessID { get; set; }
        public string CompleteBackStatus { get; set; }
        public string AdministrativeOfcDetail { get; set; }
        public string AdministrativeOfcApproveStatus { get; set; }
        public string AdministrativeOfcBackStatus { get; set; }
        public string AssitantSccDetail { get; set; }
        public string AssitantSccApproveStatus { get; set; }
        public string AssitantSccBackStatus { get; set; }
        public string SrAssitantSccDetail { get; set; }
        public string SrAssitantSccApproveStatus { get; set; }
        public string SrAssitantSccBackStatus { get; set; }
        public string DeputySecApproveDetail { get; set; }
        public string DeputySecApproveStatus { get; set; }
        public string DeputySecBackStatus { get; set; }
        public string AddSecApproveDetail { get; set; }
        public string AddSecApproveStatus { get; set; }
        public string AddSecBackStatus { get; set; }
        public string SecApproveDetail { get; set; }
        public string SecApproveStatus { get; set; }
        public string SecBackStatus { get; set; }
        public string SpeakerApproveDetail { get; set; }
        public string SpeakerApproveStatus { get; set; }
        public string SpeakerBackStatus { get; set; }
        public Nullable<int> MemberResPriority { get; set; }
    
        public virtual ResolutionApprovalMST ResolutionApprovalMST { get; set; }
    }
}
