//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Login
    {
        public Nullable<int> UserID { get; set; }
        public string EmployeeCode { get; set; }
        public string UserName { get; set; }
        public int UserLoginID { get; set; }
        public string Password { get; set; }
        public Nullable<int> Status { get; set; }
        public string UserLoginName { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public string DesignationName { get; set; }
    }
}
