//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Summary
    {
        public int MemberResolutionID { get; set; }
        public string MemberResolutionDetail { get; set; }
        public Nullable<System.DateTime> MemberResolutionDate { get; set; }
        public string RDNo { get; set; }
        public Nullable<int> ParliamentNo { get; set; }
        public Nullable<int> ParlSessID { get; set; }
        public string ParliamentBangla { get; set; }
        public Nullable<int> SessionNo { get; set; }
        public string SessionBangla { get; set; }
        public string BanglaName { get; set; }
        public string ConstitutentBangla { get; set; }
        public string ConstiBangla { get; set; }
        public string AcceptanceComment { get; set; }
        public Nullable<System.DateTime> DeputySecApproveDate { get; set; }
        public string DeputySecApproveStatus { get; set; }
        public Nullable<System.DateTime> JointSecApproveDate { get; set; }
        public string JointSecApproveStatus { get; set; }
        public Nullable<System.DateTime> SecApproveDate { get; set; }
        public string SecApproveStatus { get; set; }
        public Nullable<System.DateTime> AddSecApproveDate { get; set; }
        public string AddSecApproveStatus { get; set; }
        public Nullable<System.DateTime> SpeakerApproveDate { get; set; }
        public string SpeakerApproveStatus { get; set; }
        public Nullable<int> MemberResPriority { get; set; }
        public Nullable<System.DateTime> BallotEnglish { get; set; }
        public Nullable<int> RaisedStatus { get; set; }
        public Nullable<int> ResolutionSLNo { get; set; }
        public string SerialBangla { get; set; }
        public string BallotDate { get; set; }
        public string AddSecApproveDetail { get; set; }
        public string SpeakerApproveDetail { get; set; }
        public string SecApproveDetail { get; set; }
        public string JointSecApproveDetail { get; set; }
        public string DeputySecApproveDetail { get; set; }
    }
}
