//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMRS_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Tabular
    {
        public string BanglaName { get; set; }
        public string ConstitutentBangla { get; set; }
        public string SerialNo { get; set; }
        public string RDNo { get; set; }
        public string SelectedRD { get; set; }
        public string SelectedSL { get; set; }
        public Nullable<int> ParlSessID { get; set; }
    }
}
